создать архитектуру
aenaumov/java-explore-with-me pull request #1
Opened 2022-11-10 10:34 UTC by aenaumov

2022-11-29 07:51 UTC, db-exp requested changes

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/user/service/Impl/UserServiceImpl.java
> +    private UserRepository userRepository;
Лучше делать не через @Autowired на поле, а через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/user/UserMapper.java
> +@Component
Тут компонент по сути не нужен - все методы маппера могут быть статическими и сам класс - утилитным

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/user/model/User.java
> +public class User {
Я бы добавил аннотацию Size c ограничением как в sql и not null/null на String поля

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/user/service/Impl/UserServiceImpl.java
> +    private UserMapper userMapper;
Если он будет классом-утилитой, то здесь инжект совсем не нужен

2022-11-29 07:51 UTC, db-exp commented on server/pom.xml
> +            <version>5.0.0</version>
все конкретные версии нужно прописывать в dependancyManagement в родительском pom'е

2022-11-29 07:51 UTC, db-exp commented on server/pom.xml
> +            <version>5.0.0</version>
все конкретные версии нужно прописывать в dependancyManagement в родительском pom'е

2022-11-29 07:51 UTC, db-exp commented on server/pom.xml
> +                <version>1.1.3</version>
а это в pluginManagement

2022-11-29 07:51 UTC, db-exp commented on server/pom.xml
> +                        <version>5.0.0</version>
в dependancyManagement

2022-11-29 07:51 UTC, db-exp commented on server/src/main/java/ru/practicum/ewm/mapper/HitMapper.java
> +@Component
не особо смысла делать его компонентом, все мапперы логичней сделать классами-утилитами со статическими методами to/from

2022-11-29 07:51 UTC, db-exp commented on server/src/main/java/ru/practicum/ewm/model/Hit.java
> +    public boolean equals(Object o) {
не нужно в дипломе реализовывать equals и hashcode

2022-11-29 07:51 UTC, db-exp commented on server/src/main/java/ru/practicum/ewm/service/impl/StatisticsServiceImpl.java
> +        assert uris != null;
Лучше не дать в продакшен коде assert - для этого есть валидация запроса

2022-11-29 07:51 UTC, db-exp commented on service/pom.xml
> +            <version>5.0.0</version>
версия должна быть в dependencyManagement родительского pom'а

2022-11-29 07:51 UTC, db-exp commented on service/pom.xml
> +            <version>5.0.0</version>
версия должна быть в dependencyManagement родительского pom'а

2022-11-29 07:51 UTC, db-exp commented on service/pom.xml
> +                <version>1.1.3</version>
версия должна быть в pluginManagement родительского pom'а

2022-11-29 07:51 UTC, db-exp commented on service/pom.xml
> +                        <version>5.0.0</version>
версия должна быть в dependencyManagement родительского pom'а

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/category/CategoryMapper.java
> +public class CategoryMapper {
лучше сделать методы статическими и не создавать компонент из маппера

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/category/service/Impl/CategoryServiceImpl.java
> +    private CategoryRepository categoryRepository;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/category/service/Impl/CategoryServiceImpl.java
> +    private CategoryMapper categoryMapper;
не нужно если сделать маппер со статическими методами

2022-11-29 07:51 UTC, db-exp commented on server/src/main/java/ru/practicum/ewm/controller/HitController.java
> +    private StatisticsService statisticsService;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on server/src/main/java/ru/practicum/ewm/controller/StatsController.java
> +    private StatisticsService statisticsService;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on server/src/main/java/ru/practicum/ewm/service/impl/StatisticsServiceImpl.java
> +    StatisticsRepository statisticsRepository;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on server/src/main/java/ru/practicum/ewm/service/impl/StatisticsServiceImpl.java
> +    HitMapper hitMapper;
не нужен если сделать маппер классом со статическими методами

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/category/controller/CategoryAdminController.java
> +    private CategoryService categoryService;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/category/controller/CategoryPublicController.java
> +    private CategoryService categoryService;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/category/model/Category.java
> +    private String name;
Я бы добавил Size для валидации и явное null /not null если требуется

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/client/WebClientConfiguration.java
> +    private static final String BASE_URL = "http://ewm-server:9090";
лучше в настройки вынести

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/compilation/CompilationMapper.java
> +public class CompilationMapper {
Предлагаю не делать компонентом, а методы сделать статическими

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private String title;
Предлагаю добавить Size и null/not null

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/compilation/model/dto/CompilationDto.java
> +public class CompilationDto {
Давай разобьем на отдельные классы

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/compilation/controller/CompilationAdminController.java
> +    private CompilationService compilationService;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/compilation/controller/CompilationPublicController.java
> +    private CompilationService compilationService;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/compilation/service/Impl/CompilationServiceImpl.java
> +    private CompilationRepository compilationRepository;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/compilation/service/Impl/CompilationServiceImpl.java
> +    private EventRepository eventRepository;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/compilation/service/Impl/CompilationServiceImpl.java
> +    private CompilationMapper compilationMapper;
Уйдет, если вызвать статические методы

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/controller/EventAdminController.java
> +    private EventService eventService;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/controller/EventPrivateController.java
> +    private EventService eventService;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/controller/EventPublicController.java
> +    private EventService eventService;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +public class EventMapper {
Предлагаю убрать компонент и сделать методы статическими

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/mapper/LocationMapper.java
> +public class LocationMapper {
Предлагаю убрать компонент и сделать методы статическими

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +public class Event {
Предлагаю добавить Size null/not null на String поля

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/model/dto/EventShortDto.java
> +    private EventFullDto.CategoryEventDto category;
Не очень вариант, лучше dto сделать отдельными классами и ссылаться без вложенности

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/service/Impl/EventServiceImpl.java
> +public class EventServiceImpl implements EventService {
inject нужно делать через конструктор для все Autowired в классе

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/request/RequestMapper.java
> +public class RequestMapper {
Предлагаю методы делать статическими и не делать компонент

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/request/RequestPrivateController.java
> +    private RequestService requestService;
inject нужно делать через конструктор

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/service/Impl/EventServiceImpl.java
> +            HttpServletRequest request) {
Лучше не спускать в сервис request - получается "протекание" слоев.
Передай необходимую информацию - ip, метод итд через параметры

2022-11-29 07:51 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/request/RequestServiceImpl.java
> +public class RequestServiceImpl implements RequestService {
inject нужно делать через конструктор для всех Autowired в сервисе

2022-11-29 09:08 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/model/dto/EventShortDto.java
> +    private EventFullDto.CategoryEventDto category;
исправил.

2022-11-29 09:22 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/user/model/User.java
> +public class User {
добавил. изначально исходил из того что, entity приходит из маппера, а dto имеет проверки на размер и null

2022-11-29 09:25 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/category/model/Category.java
> +    private String name;
добавил

2022-11-29 09:26 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private String title;
добавил

2022-11-29 09:35 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/compilation/model/dto/CompilationDto.java
> +public class CompilationDto {
исправил

2022-11-29 09:35 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +public class Event {
добавил

2022-11-29 09:40 UTC, aenaumov commented on server/pom.xml
> +            <version>5.0.0</version>
исправил

2022-11-29 09:40 UTC, aenaumov commented on server/pom.xml
> +            <version>5.0.0</version>
исправил

2022-11-29 09:41 UTC, aenaumov commented on server/pom.xml
> +                <version>1.1.3</version>
исправил

2022-11-29 09:42 UTC, aenaumov commented on server/pom.xml
> +                        <version>5.0.0</version>
повторяется. было выше. уже исправил

2022-11-29 09:48 UTC, aenaumov commented on service/pom.xml
> +            <version>5.0.0</version>
исправил

2022-11-29 09:49 UTC, aenaumov commented on service/pom.xml
> +            <version>5.0.0</version>
исправил

2022-11-29 09:50 UTC, aenaumov commented on service/pom.xml
> +                <version>1.1.3</version>
исправил

2022-11-29 09:50 UTC, aenaumov commented on service/pom.xml
> +                        <version>5.0.0</version>
исправил

2022-11-29 11:08 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/user/service/Impl/UserServiceImpl.java
> +    private UserRepository userRepository;
исправил

2022-11-29 11:08 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/user/UserMapper.java
> +@Component
исправил

2022-11-29 11:09 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/user/service/Impl/UserServiceImpl.java
> +    private UserMapper userMapper;
исправил

2022-11-29 11:09 UTC, aenaumov commented on server/src/main/java/ru/practicum/ewm/mapper/HitMapper.java
> +@Component
исправил

2022-11-29 11:09 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/category/CategoryMapper.java
> +public class CategoryMapper {
исправил

2022-11-29 11:09 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/category/service/Impl/CategoryServiceImpl.java
> +    private CategoryRepository categoryRepository;
исправил

2022-11-29 11:10 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/category/service/Impl/CategoryServiceImpl.java
> +    private CategoryMapper categoryMapper;
исправил

2022-11-29 11:10 UTC, aenaumov commented on server/src/main/java/ru/practicum/ewm/controller/HitController.java
> +    private StatisticsService statisticsService;
исправил

2022-11-29 11:10 UTC, aenaumov commented on server/src/main/java/ru/practicum/ewm/controller/StatsController.java
> +    private StatisticsService statisticsService;
исправил

2022-11-29 11:10 UTC, aenaumov commented on server/src/main/java/ru/practicum/ewm/service/impl/StatisticsServiceImpl.java
> +    StatisticsRepository statisticsRepository;
исправил

2022-11-29 11:10 UTC, aenaumov commented on server/src/main/java/ru/practicum/ewm/service/impl/StatisticsServiceImpl.java
> +    HitMapper hitMapper;
исправил

2022-11-29 11:10 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/category/controller/CategoryAdminController.java
> +    private CategoryService categoryService;
исправил

2022-11-29 11:10 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/category/controller/CategoryPublicController.java
> +    private CategoryService categoryService;
исправил

2022-11-29 11:10 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/compilation/CompilationMapper.java
> +public class CompilationMapper {
исправил

2022-11-29 11:11 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/compilation/controller/CompilationAdminController.java
> +    private CompilationService compilationService;
исправил

2022-11-29 11:11 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/compilation/controller/CompilationPublicController.java
> +    private CompilationService compilationService;
исправил

2022-11-29 11:11 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/compilation/service/Impl/CompilationServiceImpl.java
> +    private CompilationRepository compilationRepository;
исправил

2022-11-29 11:11 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/compilation/service/Impl/CompilationServiceImpl.java
> +    private EventRepository eventRepository;
исправил

2022-11-29 11:11 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/compilation/service/Impl/CompilationServiceImpl.java
> +    private CompilationMapper compilationMapper;
исправил

2022-11-29 11:11 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/controller/EventAdminController.java
> +    private EventService eventService;
исправил

2022-11-29 11:11 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/controller/EventPrivateController.java
> +    private EventService eventService;
исправил

2022-11-29 11:11 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/controller/EventPublicController.java
> +    private EventService eventService;
исправил

2022-11-29 11:11 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +public class EventMapper {
исправил

2022-11-29 11:12 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/mapper/LocationMapper.java
> +public class LocationMapper {
исправил

2022-11-29 11:12 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/service/Impl/EventServiceImpl.java
> +public class EventServiceImpl implements EventService {
исправил

2022-11-29 11:12 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/request/RequestMapper.java
> +public class RequestMapper {
исправил

2022-11-29 11:12 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/request/RequestPrivateController.java
> +    private RequestService requestService;
исправил

2022-11-29 11:12 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/request/RequestServiceImpl.java
> +public class RequestServiceImpl implements RequestService {
исправил

2022-11-29 11:26 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/service/Impl/EventServiceImpl.java
> +            HttpServletRequest request) {
исправил

2022-11-29 12:02 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/client/WebClientConfiguration.java
> +    private static final String BASE_URL = "http://ewm-server:9090";
исправил

2022-11-29 12:02 UTC, aenaumov commented on server/src/main/java/ru/practicum/ewm/service/impl/StatisticsServiceImpl.java
> +        assert uris != null;
исправил

2022-11-29 12:51 UTC, aenaumov commented on server/src/main/java/ru/practicum/ewm/model/Hit.java
> +    public boolean equals(Object o) {
исправил

2022-11-29 20:31 UTC, db-exp requested changes

2022-11-29 20:31 UTC, db-exp commented on server/src/main/java/ru/practicum/ewm/mapper/HitMapper.java
> +public abstract class HitMapper {
не нужно abstract, просто public class

2022-11-29 20:31 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/category/CategoryMapper.java
> +public abstract class CategoryMapper {
лучше не надо abstract

2022-11-29 20:31 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/user/UserMapper.java
> +public abstract class UserMapper {
не надо abstract

2022-11-29 20:31 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/request/RequestMapper.java
> +public abstract class RequestMapper {
abstract)

2022-11-29 20:31 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/compilation/CompilationMapper.java
> +public abstract class CompilationMapper {
непонятно зачем abstract

2022-11-29 20:31 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/compilation/model/dto/CompilationDto.java
> +public class CompilationDto {
Вижу внутри public static class EventShortDto {

2022-11-29 20:31 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +public abstract class EventMapper {
abstract не нужно

2022-11-29 20:31 UTC, db-exp commented on service/src/main/java/ru/practicum/ewm/event/mapper/LocationMapper.java
> +public abstract class LocationMapper {
не нужно abstract

2022-11-30 07:50 UTC, aenaumov commented on server/src/main/java/ru/practicum/ewm/mapper/HitMapper.java
> +public abstract class HitMapper {
исправил

2022-11-30 07:50 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/category/CategoryMapper.java
> +public abstract class CategoryMapper {
исправил

2022-11-30 07:50 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/user/UserMapper.java
> +public abstract class UserMapper {
исправил

2022-11-30 07:50 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/request/RequestMapper.java
> +public abstract class RequestMapper {
исправил

2022-11-30 07:50 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/compilation/CompilationMapper.java
> +public abstract class CompilationMapper {
исправил

2022-11-30 07:51 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +public abstract class EventMapper {
исправил

2022-11-30 07:51 UTC, aenaumov commented on service/src/main/java/ru/practicum/ewm/event/mapper/LocationMapper.java
> +public abstract class LocationMapper {
исправил

2022-11-30 07:59 UTC, db-exp approved these changes

2022-11-30 08:36 UTC, merged